[KGA-4] [KGA-118] [KGA-119] [KGA-127] [KGA-133] fix: reentrancy check in eth_call
kkrt-labs/kakarot pull request #1582
Opened 2024-11-06 15:54 UTC by obatirou

Time spent on this PR:

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Resolves #<Issue number>

## What is the new behavior?

Reentrancy check is moved at Kakarot level in eth_call

2024-11-06 16:12 UTC, obatirou commented on cairo_zero/kakarot/library.cairo
> +from openzeppelin.security.reentrancyguard.library import ReentrancyGuard
For reference https://github.com/OpenZeppelin/cairo-contracts/blob/v0.6.1/src/openzeppelin/security/reentrancyguard/library.cairo

2024-11-06 16:53 UTC, ClementWalter requested changes
add a e2e test plz

2024-11-07 16:27 UTC, ClementWalter commented on tests/end_to_end/CairoPrecompiles/test_call_cairo_precompile.py
> +async def kakarotReentrancy(kakarot):
case

```suggestion
async def kakarot_reentrancy(kakarot):
```

2024-11-08 08:35 UTC, ClementWalter approved these changes

2024-11-08 08:35 UTC, merged