Fix testnet deploy adding gateway_client calls in kakarot.py
kkrt-labs/kakarot pull request #667
Opened 2023-07-30 22:50 UTC by devnet0x

Time spent on this PR: 0.5 days

## Pull request type

Please check the type of change your PR introduces:

- [X ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Deploy on testnet fails.

Resolves #666 

## What is the new behavior?

- Add gateway_client conditions

## Other information

Fix tested in devnet and testnet:

DEVNET:
(py39) kali:~/kakarot$ make deploy
poetry lock --check
poetry.lock is consistent with pyproject.toml.
make clean
make[1]: Entering directory '/home/kali/kakarot'
rm -rf build
mkdir build
make[1]: Leaving directory '/home/kali/kakarot'
poetry run python ./scripts/compile_kakarot.py
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI' with RPC http://127.0.0.1:5050/rpc
INFO:__main__:ℹ️  Compiling contracts for network starknet-devnet
INFO:__main__:⏳ Compiling {'contract_name': 'kakarot', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 45.90s
INFO:__main__:⏳ Compiling {'contract_name': 'blockhash_registry', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 4.13s
INFO:__main__:⏳ Compiling {'contract_name': 'contract_account', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 7.16s
INFO:__main__:⏳ Compiling {'contract_name': 'externally_owned_account', 'is_account_contract': True}
INFO:__main__:✅ Compiled in 16.14s
INFO:__main__:⏳ Compiling {'contract_name': 'proxy', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 3.49s
INFO:__main__:⏳ Compiling {'contract_name': 'EVM', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 44.72s
INFO:__main__:✅ Compiled all in 121.55s
poetry run python ./scripts/deploy_kakarot.py
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI' with RPC http://127.0.0.1:5050/rpc
INFO:__main__:ℹ️  Using account 0x7e00d496e324876bbc8531f2d9a82bf154d1a04a50218ee74cdd372f75a551a as deployer
INFO:scripts.utils.starknet:ℹ️  Declaring kakarot
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x0091a6bc98f13bd8164f4b496427fe9586a6d75a4bc74a95bc0fcb553f44a3de
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ kakarot class hash: 0x284c9954ec913534bbe7747fb3d7c2a813a8eaf28b0d9f5f601f98d7f9bc6a9
INFO:scripts.utils.starknet:ℹ️  Declaring blockhash_registry
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x017951b4598c92c879df2a0c92ab6cebbe19e0e97ca939f18a89ca9f0df62a6a
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ blockhash_registry class hash: 0x5277c32a95832978dc85642c2a99e57a04c224e1f9546c672ec7e2673ea8177
INFO:scripts.utils.starknet:ℹ️  Declaring contract_account
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x0039c6f6ac4e8f8af619a3c08a3864d16357aa58749b2b30338f7cc6500c6611
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ contract_account class hash: 0x2a8a4106311b93d77f27010f58827e02a5214bdcd92697b78e627771995899a
INFO:scripts.utils.starknet:ℹ️  Declaring externally_owned_account
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x0724c0c02fd2c0ab22385b0adedbe98e07ed4f30ef096b6068a9579695357ce7
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ externally_owned_account class hash: 0x23c39e1e3afc8845ca48d0af070825fd83d3e848f7fed5c721d5c32ba990c3f
INFO:scripts.utils.starknet:ℹ️  Declaring proxy
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x01dacae09d8814e17a2c89b08ffdfaf885a81f6d2a27c96bac25e2e957ac23a2
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ proxy class hash: 0x4b9eef81a3f0a582dfed69be93196cedbff063e0fa206b34b4c2f06ac505f0c
INFO:scripts.utils.starknet:ℹ️  Declaring EVM
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x03445d50ce841beff5e672715b1f498659e02707281ac78aa3c756f3befea633
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ EVM class hash: 0x4484d175b6a04c376a9ea1b4e21e7923f213526d334a1591c75c91e651bac89
INFO:scripts.utils.starknet:ℹ️  Deploying kakarot
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x0547453538dea1e0047448d13f376e71704bc5333cbf44a46299bcf51e3a917d
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ kakarot deployed at: 0x9aeb7e72c36edd0d2d895e9c0c0c39fdd11c470b6427bcdf1a5b713515a083
INFO:scripts.utils.starknet:ℹ️  Deploying blockhash_registry
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x05985b051976f5539b4a4f798f66235e52b890e55b75bd8aff4ea34b1cd9f4ec
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ blockhash_registry deployed at: 0x516b4ed5c1bb6b2ce67a20f3dadeefe8fbe65825f8f83464f07e5a0b3efa05b
INFO:scripts.utils.starknet:ℹ️  Deploying EVM
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x07385d4f7246b0547ccb26308c5cf51ae2fa1381eb346527e370d94c73bf0ab6
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ EVM deployed at: 0x659d6ce89385e37111c8703bf300fd0fe359fc547880f99376a48d866657830
INFO:__main__:⏳ Configuring Contracts...
INFO:scripts.utils.starknet:ℹ️  Invoking kakarot.set_blockhash_registry([2301683591891370387679197666566243653723162538194641458280194845189516271707])
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x03da9ede6f0773390163faf6368ee9e8920a5fda78214ccc1c8946b75807d275
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x03da9ede6f0773390163faf6368ee9e8920a5fda78214ccc1c8946b75807d275
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ kakarot.set_blockhash_registry invoked at tx: 0x3da9ede6f0773390163faf6368ee9e8920a5fda78214ccc1c8946b75807d275
INFO:__main__:✅ Configuration Complete
INFO:__main__:ℹ️  Found default EVM address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 to deploy an EOA for
INFO:scripts.utils.starknet:ℹ️  Invoking kakarot.deploy_externally_owned_account([1390849295786071768276380950238675083608645509734])
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x04c54567fe2793425cce1761314c65890719972b4986e27adf78fb79e3bfadc7
INFO:scripts.utils.starknet:⏳ Waiting for tx /tx/0x04c54567fe2793425cce1761314c65890719972b4986e27adf78fb79e3bfadc7
INFO:scripts.utils.starknet:ℹ️  Sleeping for 0.1s
INFO:scripts.utils.starknet:✅ kakarot.deploy_externally_owned_account invoked at tx: 0x4c54567fe2793425cce1761314c65890719972b4986e27adf78fb79e3bfadc7
INFO:scripts.utils.kakarot:ℹ️  Funding EVM address 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 at Starknet address 0x4427094e72838c8a85df1cbeb002df494f34432fa26512b5795f7062a979db
INFO:scripts.utils.starknet:1.0 ETH minted to 0x4427094e72838c8a85df1cbeb002df494f34432fa26512b5795f7062a979db
(py39) kali:~/kakarot$ 

TESTNET:
(py39) kali:~/kakarot$ STARKNET_NETWORK=testnet make deploy
poetry lock --check
poetry.lock is consistent with pyproject.toml.
make clean
make[1]: Entering directory '/home/kali/kakarot'
rm -rf build
mkdir build
make[1]: Leaving directory '/home/kali/kakarot'
poetry run python ./scripts/compile_kakarot.py
WARNING:scripts.constants:⚠️  TESTNET_ACCOUNT_ADDRESS not set, defaulting to ACCOUNT_ADDRESS
WARNING:scripts.constants:⚠️  TESTNET_PRIVATE_KEY not set, defaulting to PRIVATE_KEY
INFO:scripts.constants:ℹ️  Connected to CHAIN_ID b'SN_GOERLI' with Gateway testnet
INFO:__main__:ℹ️  Compiling contracts for network testnet
INFO:__main__:⏳ Compiling {'contract_name': 'kakarot', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 41.37s
INFO:__main__:⏳ Compiling {'contract_name': 'blockhash_registry', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 4.04s
INFO:__main__:⏳ Compiling {'contract_name': 'contract_account', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 6.29s
INFO:__main__:⏳ Compiling {'contract_name': 'externally_owned_account', 'is_account_contract': True}
INFO:__main__:✅ Compiled in 13.78s
INFO:__main__:⏳ Compiling {'contract_name': 'proxy', 'is_account_contract': False}
INFO:__main__:✅ Compiled in 3. [...]

2023-07-31 08:51 UTC, ClementWalter requested changes
Hey, thanks for your contribution. We could indeed update these kakarot utils to use the `CLIENT` and not specifically the `RPC_CLIENT`, but then you just need to update the import from `RPC_CLIENT` to `CLIENT` and update the corresponding usage!

2023-07-31 08:51 UTC, ClementWalter commented
note that this is not related to the Kakarot contract deployment but to the interaction with Kakarot once deployed

2023-07-31 23:51 UTC, devnet0x commented
Changed to CLIENT.
Testing:

Devnet Kakarot deployment:
![devnet_kakarot_deploy](https://github.com/kkrt-labs/kakarot/assets/117481421/e754609b-7b50-4fa7-aefa-6b9dc8136428)

Devnet contract deploy:
![devnet_contract_deploy](https://github.com/kkrt-labs/kakarot/assets/117481421/b7154f8c-b866-4c18-99a8-eef8f43dc4e0)

Testnet Kakarot deployment:
![testnet_kakarot_deploy](https://github.com/kkrt-labs/kakarot/assets/117481421/b1cc437c-6982-43d5-9ebb-b79b3be98169)

Testnet contract deploy:
![testnet_contract_deploy](https://github.com/kkrt-labs/kakarot/assets/117481421/9c9cb9f9-967d-4982-9367-badaa836e97a)

2023-08-01 04:44 UTC, ClementWalter approved these changes

2023-08-01 04:44 UTC, merged