Update kakarot links
kkrt-labs/kakarot pull request #884
Opened 2024-01-16 19:43 UTC by pucedoteth

i have updated the contributors link and make clickable also added Kakarot official discord.

Time spent on this PR: 0.5 day

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

you can find the official Kakarot discord and when you click on Contributors it takes you to the right page.

Resolves #<Issue number>

## What is the new behavior?

-you can find the official Kakarot discord.
-when you click on Contributors it takes you to the right page.

2024-01-17 09:42 UTC, ClementWalter requested changes
fix repo base address in github

2024-01-17 11:40 UTC, pucedoteth commented on README.md
> +[![GitHub contributors](https://img.shields.io/github/contributors/abdelhamidbakhta/kakarot?logo=github&style=flat-square)](https://github.com/abdelhamidbakhta/kakarot/graphs/contributors)
> repo is at kkrt-labs now and not abdelhamidbakhta

fixed

2024-01-17 15:40 UTC, ClementWalter requested changes
since you're making these changes, can you update all the links using abdelhamid repo instead of this one?

2024-01-18 18:43 UTC, pucedoteth commented
> fix repo base address in github

i have updated links as you requested. removed abdelhamid and insert kkrt-labs

2024-01-19 11:12 UTC, ClementWalter approved these changes

2024-01-19 11:12 UTC, merged