Mock syscalls in tests
kkrt-labs/kakarot pull request #896
Opened 2024-01-19 17:01 UTC by ClementWalter

2024-01-20 08:35 UTC, enitrat requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/896)* status: all files reviewed, 2 unresolved discussions (waiting on @ClementWalter)

___
*[`tests/fixtures/starknet.py` line 170 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot/896#-Noa-7iKB0vjj2yxCQIh:-Noa-7iKB0vjj2yxCQIi:b-9t3vt4) ([raw file](https://github.com/kkrt-labs/kakarot/blob/8bbdfd7d08e1590854e2ab2d841c0a16503d1c01/tests/fixtures/starknet.py#L170)):*
> ```Python
>             ScopedName(path=["__main__", entrypoint, "ImplicitArgs"])
>         ).members.keys()
>         # Fix builtins runner based on the implicit args since the compiler doesn't find them
> ```

Does this mean that using something like `%builtin range_check` is not required in pure cairo test files?
___
*[`tests/utils/syscall_handler.py` line 84 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot/896#-Noa-fqj307e08_9t2N9:-Noa-fqj307e08_9t2NA:b-5y0xsf) ([raw file](https://github.com/kkrt-labs/kakarot/blob/8bbdfd7d08e1590854e2ab2d841c0a16503d1c01/tests/utils/syscall_handler.py#L84)):*
> ```Python
>         function_selector = segments.memory[syscall_ptr + 2]
>         if function_selector == get_selector_from_name("balanceOf"):
>             retdata = [2, 0]
> ```

why these values specifically?


<!-- Sent from Reviewable.io -->

2024-01-23 08:38 UTC, enitrat submitted a review, later dismissed

2024-01-23 08:40 UTC, enitrat commented on tests/utils/syscall_handler.py
> +            Note than when patching a contract call, only the last part of the target is used.
```suggestion
            Note that when patching a contract call, only the last part of the target is used.
```

2024-01-23 08:51 UTC, ClementWalter reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot/896)* status: 3 of 16 files reviewed, 3 unresolved discussions (waiting on @enitrat)

___
*[`tests/fixtures/starknet.py` line 170 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot/896#-Noa-7iKB0vjj2yxCQIh:-NopVooZBf721whxxxFL:b-7k232j) ([raw file](https://github.com/kkrt-labs/kakarot/blob/8bbdfd7d08e1590854e2ab2d841c0a16503d1c01/tests/fixtures/starknet.py#L170)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

Does this mean that using something like `%builtin range_check` is not required in pure cairo test files?
</blockquote></details>

if the program doesn't use the range_check, it's not required no afaik
___
*[`tests/utils/syscall_handler.py` line 84 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot/896#-Noa-fqj307e08_9t2N9:-NopW0EW8LWTk8ez4mE1:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot/blob/8bbdfd7d08e1590854e2ab2d841c0a16503d1c01/tests/utils/syscall_handler.py#L84)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

why these values specifically?
</blockquote></details>

Done.
___
*[`tests/utils/syscall_handler.py` line 164 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot/896#gh-1462911038:-NopW1woCEG5SJnYB0mX:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot/blob/710a02946a6a017c2a630d332141a864dbc3057f/tests/utils/syscall_handler.py#L164)):*
<details><summary><i>Previously, enitrat (Mathieu) wrote…</i></summary><blockquote>

```suggestion
            Note that when patching a contract call, only the last part of the target is used.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 09:02 UTC, merged